spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
