version: '3.7'

services:
  licenseservice:
    image: vula/license-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"    
    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
  backend:
    driver: bridge
